"""Initial schema (STOPGAP).
Creates all tables from the SQLAlchemy metadata. Before production, replace with an autogenerated,
explicit migration:  rm this file && alembic revision --autogenerate -m initial
"""
from alembic import op
revision = "0001"; down_revision = None; branch_labels = None; depends_on = None

def upgrade():
    from app.db.session import Base
    import app.models  # noqa
    Base.metadata.create_all(bind=op.get_bind())

def downgrade():
    from app.db.session import Base
    import app.models  # noqa
    Base.metadata.drop_all(bind=op.get_bind())
